import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://cincainame.vercel.app/');
  await page.getByRole('link', { name: 'About Me' }).click();
  await page.locator('h1').filter({ hasText: 'Lee Jia Jun' }).click();
  await page.getByRole('heading', { name: 'Software Engineer', exact: true }).click();
  await page.getByText('I\'m Lee Jia Jun, a software').click();
  await page.locator('.rounded-2xl').first().click();
  await page.getByRole('heading', { name: 'Tools and Technologies' }).click();
  await page.getByRole('paragraph').filter({ hasText: /^Azure$/ }).click();
  await page.getByRole('paragraph').filter({ hasText: 'Azure DevOps' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'Python' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'HTML' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'CSS' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'Sass' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'Tailwind' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'Bootstrap' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'JavaScript' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'NodeJS' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'TypeScript' }).click();
  await page.getByRole('paragraph').filter({ hasText: /^React$/ }).click();
  await page.getByRole('paragraph').filter({ hasText: 'Vite' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'Express' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'Postgresql' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'Swagger' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'Postman' }).click();
  await page.getByRole('paragraph').filter({ hasText: /^\.NET$/ }).click();
  await page.getByRole('paragraph').filter({ hasText: /^C#$/ }).click();
  await page.getByRole('paragraph').filter({ hasText: 'C++' }).click();
  await page.getByRole('paragraph').filter({ hasText: /^Java$/ }).click();
  await page.getByRole('paragraph').filter({ hasText: 'Visual Basic' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'Flutter' }).click();
  await page.getByRole('paragraph').filter({ hasText: /^Firebase$/ }).click();
  await page.getByRole('paragraph').filter({ hasText: /^Git$/ }).click();
  await page.getByRole('paragraph').filter({ hasText: 'Github' }).click({
    button: 'right'
  });
  await page.getByRole('paragraph').filter({ hasText: 'Github' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'MySQL' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'PHP' }).click();
  await page.getByRole('paragraph').filter({ hasText: /^Visual Studio$/ }).click();
  await page.getByRole('paragraph').filter({ hasText: 'Visual Studio Code' }).click();
  await page.getByRole('paragraph').filter({ hasText: /^R$/ }).click();
  await page.getByRole('paragraph').filter({ hasText: 'Grunt' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'Vercel' }).click();
  await page.getByRole('heading', { name: 'Education' }).click();
  await page.getByText('Asia Pacific University/JAN').click();
  await page.getByRole('heading', { name: 'Bachelor of Software' }).click();
  await page.locator('.w-30').first().click();
  await page.getByText('Currently pursuing a').click();
  await page.getByText('Asia Pacific University/OCT').click();
  await page.getByRole('heading', { name: 'Diploma in ICT specialism in' }).click();
  await page.locator('div:nth-child(2) > .pb-5 > div:nth-child(2) > .w-30').click();
  await page.getByText('Completed foundational').click();
  await page.locator('h2').filter({ hasText: 'Lee Jia Jun' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link').filter({ hasText: /^$/ }).first().click();
  const page1 = await page1Promise;
  await page.getByText('EMAIL ME: leejiajun04@gmail.').click();
  await page.getByText('CALL ME:+6011-').click();
  await page.getByText('© 2025 Lee Jia Jun. All').click();
});